### ISSUE TITLE
How to verify rolls?

### ISSUE THREAD

**Issue by wargamesqcf** [TerenceJefferies/mybbDiceRoller#1]
I have the salt, and the hash so where/how do I verify the roll?

**Comment by TerenceJefferies** [comment]
The hash is designed to only be verified on posts you find suspicious, but it is an amalgamation of the post ID and the secret salt. 

If you, in your dev environment, or by any other means, take your salt and append the post ID to the end and sha1 it, the resulting string should match the hash in the post - That way, as long as no-one knows your salt, you can compare the two, if they match, you know the roll was genuine.

**Comment by wargamesqcf** [comment]
yep that works, thanks. now just to change to dice rolling part to the l5r system.
